### PR TITLE
lib/client: fix stalls with large payloads

### PR DESCRIPTION
**Pull request by bnoordhuis**
Replace call to net.Socket#destroy() with net.Socket#destroySoon();
the former closes the connection immediately while the latter waits
until any pending writes have been written.

Point of action: calling send() + disconnect() before the 'connect'
event has been emitted still doesn't work.

Suggested reviewers: @Qard @themitchy

### CODE REVIEW

**Comment by slnode** [comment]
Test PASSed. To trigger a build add comment - "._test\W+please_"
Refer to this link for build results: http://ci.strongloop.com/job/uhura/42/

**Comment by slnode** [comment]
Test PASSed. To trigger a build add comment - "._test\W+please_"
Refer to this link for build results: http://ci.strongloop.com/job/uhura/43/

**Comment by themitchy** [comment]
LGTM

**Comment by bnoordhuis** [comment]
Cheers, landed in 86c9188.

**Pull request merged**
