### PR TITLE
lib: make connection type configurable

### PR DESCRIPTION
**Pull request by bnoordhuis**
It's now possible for the caller to create the socket/server object that
Uhura uses.  First step in making it possible to use SSL/TLS encryption.

Suggested reviewers: @themitchy @Qard

TODO: Update the README.  I'll do that if you guys think this is a decent approach.

### CODE REVIEW

**Comment by slnode** [comment]
Test PASSed. To trigger a build add comment - "._test\W+please_"
Refer to this link for build results: http://ci.strongloop.com/job/uhura/46/

**Comment by bnoordhuis** [comment]
Last call for review.

**Comment by themitchy** [comment]
LGTM

**Comment by bnoordhuis** [comment]
Cheers Mitch, landed in f7d00f0.

**Pull request merged**
