### PR TITLE
lib/client: make createConnection callback-driven

### PR DESCRIPTION
**Pull request by bnoordhuis**
Plus commits that add ref/unref methods to uhura.Client and tidy up the timer unref hack from ef477d1.

Suggested reviewer: @themitchy

### CODE REVIEW

**Comment by slnode** [comment]
Test PASSed. To trigger a build add comment - "._test\W+please_"
Refer to this link for build results: http://ci.strongloop.com/job/uhura/50/

**Comment by sam-github** [comment]
LGTM

**Comment by sam-github** [comment]
But API is incompatible, don't forget to increment version minor in package.json

**Comment by bnoordhuis** [comment]
Cheers, landed.

> But API is incompatible, don't forget to increment version minor in package.json

I don't think that's necessary, createConnection hasn't made its way into a release yet.

**Comment by bnoordhuis** [comment]
Released as v0.1.1.  I also added all missing tags, the only release so far that had a tag was v0.0.7.

**Pull request merged**
