### PR TITLE
lib: handle JSON parse errors

### PR DESCRIPTION
**Pull request by bnoordhuis**
Don't throw an uncatchable exception when the input is malformed JSON.
Forward the exception as an 'error' event that the user can handle or
ignore as s/he sees fit.

Suggested reviewers: @themitchy @Qard.  Without this patch it's dead simple to bring down the nodefly-collector (accidentally or otherwise.)

### CODE REVIEW

**Comment by slnode** [comment]
Test PASSed. To trigger a build add comment - "._test\W+please_"
Refer to this link for build results: http://ci.strongloop.com/job/uhura/38/

**Comment by slnode** [comment]
Test PASSed. To trigger a build add comment - "._test\W+please_"
Refer to this link for build results: http://ci.strongloop.com/job/uhura/39/

**Comment by themitchy** [comment]
LGTM

**Comment by bnoordhuis** [comment]
Cheers, landed in 09e2c31.

**Comment by Qard** [comment]
Good catch. Not sure how I missed that.

**Pull request merged**
