### PR TITLE
Make things work better on CI

### PR DESCRIPTION
**Pull request by rmg**
/cc @themitchy @Qard @sam-github

### CODE REVIEW

**Comment by slnode** [comment]
Test FAILed. To trigger a build add comment - "._test\W+please_"
Refer to this link for build results: http://ci.strongloop.com/job/uhura/28/

**Comment by slnode** [comment]
Test FAILed. To trigger a build add comment - "._test\W+please_"
Refer to this link for build results: http://ci.strongloop.com/job/uhura/29/

**Comment by rmg** [comment]
test please

**Comment by slnode** [comment]
Test FAILed. To trigger a build add comment - "._test\W+please_"
Refer to this link for build results: http://ci.strongloop.com/job/uhura/30/

**Comment by rmg** [comment]
test please

**Comment by slnode** [comment]
Test FAILed. To trigger a build add comment - "._test\W+please_"
Refer to this link for build results: http://ci.strongloop.com/job/uhura/31/

**Comment by rmg** [comment]
test please

**Comment by slnode** [comment]
Test PASSed. To trigger a build add comment - "._test\W+please_"
Refer to this link for build results: http://ci.strongloop.com/job/uhura/32/

**Comment by slnode** [comment]
Test PASSed. To trigger a build add comment - "._test\W+please_"
Refer to this link for build results: http://ci.strongloop.com/job/uhura/33/

**Comment by slnode** [comment]
Test PASSed. To trigger a build add comment - "._test\W+please_"
Refer to this link for build results: http://ci.strongloop.com/job/uhura/35/

**Comment by sam-github** [comment]
Where's this at?

**Comment by slnode** [comment]
Test PASSed. To trigger a build add comment - "._test\W+please_"
Refer to this link for build results: http://ci.strongloop.com/job/uhura/51/

**Comment by rmg** [comment]
@sam-github among the cluster of test comments I don't see anyone approving the PR. Since this hasn't been merged, I just pushed some amendments.

**Comment by sam-github** [comment]
LGTM

**Comment by rmg** [comment]
Squashed and merged in 54986e6.

**Pull request closed without merging**
